### ISSUE TITLE
运行node main时候报错

### ISSUE THREAD

**Issue by chenyl107** [NetEase/pomelo-robot-demo#2]
chendeMacBook-Pro:~ xiaohei107$ sudo npm install pomelo-robot
Password:
npm http GET https://registry.npmjs.org/pomelo-robot
npm http 200 https://registry.npmjs.org/pomelo-robot
npm http GET https://registry.npmjs.org/pomelo-robot/-/pomelo-robot-0.0.27.tgz
npm http 200 https://registry.npmjs.org/pomelo-robot/-/pomelo-robot-0.0.27.tgz
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/socket.io-client
npm http GET https://registry.npmjs.org/socket.io
npm http GET https://registry.npmjs.org/pomelo-protocol
npm http 304 https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/socket.io-client
npm http 304 https://registry.npmjs.org/pomelo-protocol
npm http GET https://registry.npmjs.org/pomelo-protocol/-/pomelo-protocol-0.0.2.tgz
npm http 200 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.4.2.tgz
npm http 200 https://registry.npmjs.org/pomelo-protocol/-/pomelo-protocol-0.0.2.tgz
npm WARN package.json pomelo-protocol@0.0.2 No README.md file found!
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.4.2.tgz
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/redis/0.7.3
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/tinycolor

> ws@0.4.23 install /Users/xiaohei107/node_modules/pomelo-robot/node_modules/socket.io-client/node_modules/ws
> node install.js

[ws v0.4.23] Attempting to compile blazing fast native extensions.
[ws v0.4.23] Native extension compilation successful!
pomelo-robot@0.0.27 node_modules/pomelo-robot
├── pomelo-protocol@0.0.2
├── underscore@1.4.2
├── socket.io@0.9.11 (policyfile@0.0.4, redis@0.7.3)
└── socket.io-client@0.9.11 (xmlhttprequest@1.4.2, uglify-js@1.2.5, active-x-obfuscator@0.0.1, ws@0.4.23)

chendeMacBook-Pro:~ xiaohei107$ node main

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/xiaohei107/main'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

**Comment by piaohai** [comment]
运行时，请确认当前目前下是否有main.js，没有的话，请进行到有这个文件的目录。
